---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
      KeyName: AnsibleEC2
      InstanceType: t2.micro
      SSHLocation: 0.0.0.0/0

  tasks:
      - name: Run Ansible host cloudformation stack
        cloudformation: 
            stack_name: "AnsibleHostStack"
            region: "eu-central-1"
            state: "present"
            template: "EC2Instance.template"
            template_parameters:
            KeyName: ""
            InstanceType: ""
            SSHLocation: ""
            tags: 
                env: "test"
                stack: "ansible"
        register: ansiblehost_stack
      - debug: msg=""
      - debug: msg=""

